### ISSUE TITLE
Getting unlimited amount of keystrokes

### ISSUE THREAD

**Issue by muefabian** [cobrce/interception_py#2]
When I run an example, I can't do anything because I'm getting keystrokes non-stop. Do you know what could cause this? 
I can use the interception lib in C++ without a problem.

**Comment by cobrce** [comment]
The python code is a port of the C one and I never had this problem, without enough information the bug is not reproducible and there is no way to debug it.
Did you have the same issue with all the examples?

**Comment by MatejKafka** [comment]
I encountered the same issue - it seems that interception driver inserts the synthesized keystrokes before itself, so it receives them again, resulting in an infinite loop.

**Comment by cobrce** [comment]
Apparently the issue happens only in python3 x64, I could reproduce it and fixed it, please try the latest commit and tell me if the problem is gone
